### PR TITLE
Totalalloc

### LINKED ISSUE #4: Add totalcalc to validate total storage available after storage claims
WIP calcs
cluster_storage = len(raw_devices) * raw_storage_size * len(app_hosts)
                block_calc = registry_pvsize + block_host_size
                totalcalc = block_calc
                if totalcalc < cluster_storage :
                        print "cluster_storage=%d" % cluster_storage
                        print "totalstoragecalc=%d" % totalcalc
                        print "\033[91m Total Storage is Oversubscribed \033[0m"
                        print "\033[91m Please provision the storage \033[0m"
                        print "Total storage calc = block_host_vol_size (if it exists) \n"
                        print "+registry PV < sum of storage devices per node \033[0m"
                        exit()

### PR DESCRIPTION
**Pull request by ramkrsna**
This resolves #4  . Needs review

### CODE REVIEW

**Comment by netzzer** [comment]
Issue with Cluster 1. Available storage = 100GB, not 133GB. It looks like there is 30% added?
How many nodes are available ?:  7
What hosts will be used for application storage (IP/FQDN) ?: aaa.com bbb.com ccc.com ddd.com
What are the raw storage devices for these hosts(/dev/<device>) ?: /dev/sdb
What is the size of each raw storage device (GB) ?: 100
What is the size for the registry persistent volume (GB)?: 10
How many replicas for logging ?: 50
What is the size for each logging persistent volume (GB) ?: 3
What is the size for each metrics persistent volume (GB) ?: 20
What hosts will be used for CNS logging + metrics backend storage  (IP/FQDN) ?:  fff.com ggg.com hhh.com
What are the raw storage devices for logging + metrics backend on these hosts (/dev/<device>) ?: /dev/sdb
What is the size of each raw storage device (GB) ? : 100
# * 
# Cluster 1
# Total Storage allocated (GB) = 0
# Total Storage available (GB) = 133
# Cluster 2
# Total Storage allocated (GB) = 231
# Total Storage available (GB) = 100

**Comment by netzzer** [comment]
The Warning is good but should be all on one line or at least not have blank lines inserted in the middle of the statement.
```
How many nodes are available ?:  3
What hosts will be used for application storage (IP/FQDN) ?: aaa.com bbb.com ccc.com
What are the raw storage devices for these hosts(/dev/<device>) ?: /dev/sdb /dev/sdc
What is the size of each raw storage device (GB) ?: 100
What is the size for the registry persistent volume (GB)?: 200
How many replicas for logging ?: 3
What is the size for each logging persistent volume (GB) ?: 20
# Cluster 1
# Total Storage allocated (GB) = 278
# Total Storage available (GB) = 200
Warning one or more persistent volumes are 

larger than the raw storage device size
```

**Comment by netzzer** [comment]
Might be good to add the

**Comment by netzzer** [comment]
Please leave a blank line before and after Cluster1 and Cluster2 reporting. Also get rid of the '*' for some of the scenarios (e.g., choice 3, 4 two cluster).

**Comment by ramkrsna** [comment]
@netzzer The 133 GB is due to 4 nodes x 1 device x 100 = 400 / 3.0 (replica 3) = 133 . I believe the total storage available is 133 GB.

**Comment by netzzer** [comment]
Yes, Ramky, You are right about the 4 node condition that if storage device = 100GB then available storage for 4 nodes = 100GBx4 / 3 = 133 GB. My bad.

**Comment by netzzer** [comment]
Thinking we should add another warning if storage is oversubscribed in addition to having a PV size larger than the storage device. Something like this.
```
Enter your choice [1-5] : 4
------------------------------------------------------------
For this configuration 7 nodes are recommended
With a minimum of 3 required 
------------------------------------------------------------
How many nodes are available ?:  3                    
What hosts will be used for application storage (IP/FQDN) ?: aaa.com bbb.com ccc.com
What are the raw storage devices for these hosts(/dev/<device>) ?: /dev/sdb
What is the size of each raw storage device (GB) ?: 100
What is the size for the registry persistent volume (GB)?: 50
How many replicas for logging ?: 3
What is the size for each logging persistent volume (GB) ?: 50
What is the size for each metrics persistent volume (GB) ?: 20
# Cluster 1
# Total Storage allocated (GB) = 271
# Total Storage available (GB) = 100
Warning your Total Storage available is less than the Total Storage allocated
```

**Comment by netzzer** [comment]
This is not correct. There should be no Warning for the size of the PV. The 2nd cluster is used for the registry + metrics PV and the storage size = 200 GB. Therefore, 150 GB size for registry PV is NOT larger than 200 GB. (The Warning about Available Storage less than Allocated Storage would apply though).
````
Enter your choice [1-5] : 3
------------------------------------------------------------
For this configuration 7 nodes are recommended
With a minimum of 3 required 
------------------------------------------------------------
How many nodes are available ?:  7
What hosts will be used for application storage (IP/FQDN) ?: aaa.com bbb.com ccc.com
What are the raw storage devices for these hosts(/dev/<device>) ?: /dev/sdb
What is the size of each raw storage device (GB) ?: 100
What is the size for the registry persistent volume (GB)?: 150
What is the size for each metrics persistent volume (GB) ?: 20 
What hosts will be used for CNS metrics backend storage  (IP/FQDN) ?:  ddd.com fff.com ggg.com hhh.com
What are the raw storage devices for metrics backend on these hosts (/dev/<device>) ?: /dev/sdb
What is the size of each raw storage device (GB) ? : 200
# Cluster 1
# Total Storage allocated (GB) = 0
# Total Storage available (GB) = 100
   
# Cluster 2
# Total Storage allocated (GB) = 176
# Total Storage available (GB) = 266
Warning one or more persistent volumes are
larger than the raw storage device size
```

**Comment by netzzer** [comment]
Going to go ahead and merge. Any new fixes should go in new PR.

**Comment by netzzer** [comment]
This is working better but need to add blank line now between cluster info and the inventory file options.
```
Enter your choice [1-5] : 3
------------------------------------------------------------
For this configuration 7 nodes are recommended
With a minimum of 3 required 
------------------------------------------------------------
How many nodes are available ?:  6
What hosts will be used for application storage (IP/FQDN) ?: aaa.com bbb.com ccc.com
What are the raw storage devices for these hosts(/dev/<device>) ?: /dev/xvdf
What is the size of each raw storage device (GB) ?: 100
What is the size for the registry persistent volume (GB)?: 150
What is the size for each metrics persistent volume (GB) ?: 20
What hosts will be used for CNS metrics backend storage  (IP/FQDN) ?:  ddd.com eee.com fff.com
What are the raw storage devices for metrics backend on these hosts (/dev/<device>) ?: /dev/xvdf
What is the size of each raw storage device (GB) ? : 200
# Cluster 1
# Total Storage allocated (GB) = 0
# Total Storage available (GB) = 100
   
# Cluster 2
# Total Storage allocated (GB) = 176
# Total Storage available (GB) = 200
[OSEv3:children]
 
```

**Pull request merged**
